# -*- coding: utf-8 -*-
import os
import django
import sys
sys.path.append('C:/Users/emili/workspace/project-django-vue/blog-rest-vue/backend')

# Configura la configuración de Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from blog.models import Tag

tags = [
    { "title": "Tecnología", "slug": "tecnologia" },
    { "title": "Ciencia", "slug": "ciencia" },
    { "title": "Arte", "slug": "arte" },
    { "title": "Literatura", "slug": "literatura" },
    { "title": "Viajes", "slug": "viajes" },
    { "title": "Historia", "slug": "historia" },
    { "title": "Cultura", "slug": "cultura" },
    { "title": "Música", "slug": "musica" },
    { "title": "Cine", "slug": "cine" },
    { "title": "Fotografía", "slug": "fotografia" },
    { "title": "Moda", "slug": "moda" },
    { "title": "Cocina", "slug": "cocina" },
    { "title": "Salud", "slug": "salud" },
    { "title": "Fitness", "slug": "fitness" },
    { "title": "Deportes", "slug": "deportes" },
    { "title": "Finanzas", "slug": "finanzas" },
    { "title": "Negocios", "slug": "negocios" },
    { "title": "Marketing", "slug": "marketing" },
    { "title": "Educación", "slug": "educacion" },
    { "title": "Psicología", "slug": "psicologia" },
    { "title": "Espiritualidad", "slug": "espiritualidad" },
    { "title": "Filosofía", "slug": "filosofia" },
    { "title": "Medio Ambiente", "slug": "medio-ambiente" },
    { "title": "Política", "slug": "politica" },
    { "title": "Derechos Humanos", "slug": "derechos-humanos" },
    { "title": "Justicia Social", "slug": "justicia-social" },
    { "title": "Viajes Espaciales", "slug": "viajes-espaciales" },
    { "title": "Astronomía", "slug": "astronomia" },
    { "title": "Ecología", "slug": "ecologia" },
    { "title": "Tecnología Blockchain", "slug": "tecnologia-blockchain" },
    { "title": "Animales", "slug": "animales" },
    { "title": "Automóviles", "slug": "automoviles" },
    { "title": "Moda", "slug": "moda" },
    { "title": "Entretenimiento", "slug": "entretenimiento" },
    { "title": "Salud Mental", "slug": "salud-mental" },
    { "title": "Diseño", "slug": "diseno" },
    { "title": "Alimentación", "slug": "alimentacion" },
    { "title": "Belleza", "slug": "belleza" },
    { "title": "Historia del Arte", "slug": "historia-del-arte" },
    { "title": "Política Internacional", "slug": "politica-internacional" },
    { "title": "Robótica", "slug": "robotica" },
    { "title": "Innovación", "slug": "innovacion" },
    { "title": "Juegos", "slug": "juegos" },
    { "title": "Desarrollo Personal", "slug": "desarrollo-personal" },
    { "title": "Religión", "slug": "religion" },
    { "title": "Arquitectura", "slug": "arquitectura" },
    { "title": "Negocios Internacionales", "slug": "negocios-internacionales" },
    { "title": "Economía", "slug": "economia" },
    { "title": "Medicina", "slug": "medicina" },
    { "title": "Viajes", "slug": "viajes" },
    { "title": "Aventura", "slug": "aventura" },
    { "title": "Viajes", "slug": "viajes" },
    { "title": "Diversión", "slug": "diversion" },
    { "title": "Educación Financiera", "slug": "educacion-financiera" },
    { "title": "Salud Física", "slug": "salud-fisica" },
    { "title": "Inspiración", "slug": "inspiracion" },
    { "title": "Meditación", "slug": "meditacion" },
    { "title": "Creatividad", "slug": "creatividad" },
    { "title": "Desarrollo de Software", "slug": "desarrollo-de-software" },
    { "title": "Programación", "slug": "programacion" },
    { "title": "Tecnología de la Información", "slug": "tecnologia-de-la-informacion" },
    { "title": "Inteligencia Artificial", "slug": "inteligencia-artificial" },
    { "title": "Realidad Virtual", "slug": "realidad-virtual" },
    { "title": "Realidad Aumentada", "slug": "realidad-aumentada" },
    { "title": "Machine Learning", "slug": "machine-learning" },
    { "title": "Deep Learning", "slug": "deep-learning" },
    { "title": "Redes Neuronales", "slug": "redes-neuronales" },
    { "title": "Big Data", "slug": "big-data" },
    { "title": "Análisis de Datos", "slug": "analisis-de-datos" },
    { "title": "Blockchain", "slug": "blockchain" },
    { "title": "Criptomonedas", "slug": "criptomonedas" },
    { "title": "Ethereum", "slug": "ethereum" },
    { "title": "Bitcoin", "slug": "bitcoin" },
    { "title": "Cripto Trading", "slug": "cripto-trading" },
    { "title": "Finanzas Personales", "slug": "finanzas-personales" },
    { "title": "Inversiones", "slug": "inversiones" },
    { "title": "Bolsa de Valores", "slug": "bolsa-de-valores" },
    { "title": "Emprendimiento", "slug": "emprendimiento" },
    { "title": "Startups", "slug": "startups" },
    { "title": "Negocios Online", "slug": "negocios-online" },
    { "title": "Marketing Digital", "slug": "marketing-digital" },
    { "title": "SEO", "slug": "seo" },
    { "title": "Social Media", "slug": "social-media" },
    { "title": "Publicidad", "slug": "publicidad" },
    { "title": "Ventas", "slug": "ventas" },
    { "title": "Recursos Humanos", "slug": "recursos-humanos" },
    { "title": "Gestión del Tiempo", "slug": "gestion-del-tiempo" },
    { "title": "Productividad", "slug": "productividad" },
    { "title": "Liderazgo", "slug": "liderazgo" },
    { "title": "Trabajo en Equipo", "slug": "trabajo-en-equipo" },
    { "title": "Motivación", "slug": "motivacion" },
    { "title": "Comunicación", "slug": "comunicacion" },
    { "title": "Networking", "slug": "networking" },
    { "title": "Habilidades Sociales", "slug": "habilidades-sociales" },
    { "title": "Idiomas", "slug": "idiomas" },
    { "title": "Cultura General", "slug": "cultura-general" },
    { "title": "Curiosidades", "slug": "curiosidades" },
    { "title": "Humor", "slug": "humor" },
    { "title": "Noticias", "slug": "noticias" },
    { "title": "Tecnología", "slug": "tecnologia" },
    { "title": "Innovación", "slug": "innovacion" },
    { "title": "Emprendimiento", "slug": "emprendimiento" },
    { "title": "Desarrollo Personal", "slug": "desarrollo-personal" },
    { "title": "Motivación", "slug": "motivacion" },
    { "title": "Productividad", "slug": "productividad" },
    { "title": "Creatividad", "slug": "creatividad" },
    { "title": "Marketing", "slug": "marketing" },
    { "title": "Ventas", "slug": "ventas" },
    { "title": "Finanzas", "slug": "finanzas" },
    { "title": "Negocios", "slug": "negocios" },
    { "title": "Gestión del Tiempo", "slug": "gestion-del-tiempo" },
    { "title": "Recursos Humanos", "slug": "recursos-humanos" },
    { "title": "Liderazgo", "slug": "liderazgo" },
    { "title": "Comunicación", "slug": "comunicacion" },
    { "title": "Desarrollo Web", "slug": "desarrollo-web" },
    { "title": "Diseño Web", "slug": "diseno-web" },
    { "title": "Programación", "slug": "programacion" },
    { "title": "JavaScript", "slug": "javascript" },
    { "title": "Python", "slug": "python" },
    { "title": "HTML", "slug": "html" },
    { "title": "CSS", "slug": "css" },
    { "title": "React", "slug": "react" },
    { "title": "Angular", "slug": "angular" },
    { "title": "Vue.js", "slug": "vue-js" },
    { "title": "Node.js", "slug": "node-js" },
    { "title": "Django", "slug": "django" },
    { "title": "Flask", "slug": "flask" },
    { "title": "Ruby on Rails", "slug": "ruby-on-rails" },
    { "title": "WordPress", "slug": "wordpress" },
    { "title": "Joomla", "slug": "joomla" },
    { "title": "Drupal", "slug": "drupal" },
    { "title": "E-commerce", "slug": "e-commerce" },
    { "title": "SEO", "slug": "seo" },
    { "title": "SEM", "slug": "sem" },
    { "title": "Social Media", "slug": "social-media" },
    { "title": "Email Marketing", "slug": "email-marketing" },
    { "title": "Marketing de Contenidos", "slug": "marketing-de-contenidos" },
    { "title": "Marketing de Afiliados", "slug": "marketing-de-afiliados" },
    { "title": "Marketing Digital", "slug": "marketing-digital" },
    { "title": "Marketing de Influencia", "slug": "marketing-de-influencia" },
    { "title": "Publicidad Online", "slug": "publicidad-online" },
    { "title": "Analítica Web", "slug": "analitica-web" },
    { "title": "Growth Hacking", "slug": "growth-hacking" },
    { "title": "Startups", "slug": "startups" },
    { "title": "Emprendimiento", "slug": "emprendimiento" },
    { "title": "Business Intelligence", "slug": "business-intelligence" },
    { "title": "Big Data", "slug": "big-data" },
    { "title": "Inteligencia Artificial", "slug": "inteligencia-artificial" },
    { "title": "Machine Learning", "slug": "machine-learning" },
    { "title": "Deep Learning", "slug": "deep-learning" },
    { "title": "Blockchain", "slug": "blockchain" },
    { "title": "Criptomonedas", "slug": "criptomonedas" },
    { "title": "Fintech", "slug": "fintech" },
    { "title": "Banca Digital", "slug": "banca-digital" },
    { "title": "Pagos Electrónicos", "slug": "pagos-electronicos" },
    { "title": "Banca Online", "slug": "banca-online" },
    { "title": "Banca Móvil", "slug": "banca-movil" },
    { "title": "Inversiones", "slug": "inversiones" },
    { "title": "Trading", "slug": "trading" },
    { "title": "Economía", "slug": "economia" },
    { "title": "Finanzas Personales", "slug": "finanzas-personales" },
    { "title": "Planificación Financiera", "slug": "planificacion-financiera" },
    { "title": "Educación Financiera", "slug": "educacion-financiera" },
    { "title": "Asesoramiento Financiero", "slug": "asesoramiento-financiero" },
    { "title": "Impuestos", "slug": "impuestos" },
    { "title": "Contabilidad", "slug": "contabilidad" },
    { "title": "Gestión de Proyectos", "slug": "gestion-de-proyectos" },
    { "title": "Metodologías Ágiles", "slug": "metodologias-agiles" },
    { "title": "Scrum", "slug": "scrum" },
    { "title": "Kanban", "slug": "kanban" },
    { "title": "Lean", "slug": "lean" },
    { "title": "Project Management", "slug": "project-management" },
    { "title": "Gestión del Cambio", "slug": "gestion-del-cambio" },
    { "title": "Gestión de Equipos", "slug": "gestion-de-equipos" },
    { "title": "Desarrollo Organizacional", "slug": "desarrollo-organizacional" },
    { "title": "Liderazgo", "slug": "liderazgo" },
    { "title": "Coaching", "slug": "coaching" },
    { "title": "Mentoría", "slug": "mentoria" },
    { "title": "Recursos Humanos", "slug": "recursos-humanos" },
    { "title": "Selección de Personal", "slug": "seleccion-de-personal" },
    { "title": "Desarrollo de Carrera", "slug": "desarrollo-de-carrera" },
    { "title": "Cultura Organizacional", "slug": "cultura-organizacional" },
    { "title": "Gestión del Talento", "slug": "gestion-del-talento" },
    { "title": "Compensación y Beneficios", "slug": "compensacion-y-beneficios" },
    { "title": "Relaciones Laborales", "slug": "relaciones-laborales" },
    { "title": "Legislación Laboral", "slug": "legislacion-laboral" },
    { "title": "Seguridad Laboral", "slug": "seguridad-laboral" },
    { "title": "Prevención de Riesgos Laborales", "slug": "prevencion-de-riesgos-laborales" },
    { "title": "Ergonomía", "slug": "ergonomia" },
    { "title": "Seguridad e Higiene", "slug": "seguridad-e-higiene" },
    { "title": "Medio Ambiente", "slug": "medio-ambiente" },
    { "title": "Sostenibilidad", "slug": "sostenibilidad" },
    { "title": "Energías Renovables", "slug": "energias-renovables" },
    { "title": "Cambio Climático", "slug": "cambio-climatico" },
    { "title": "Reciclaje", "slug": "reciclaje" },
    { "title": "Gestión de Residuos", "slug": "gestion-de-residuos" },
    { "title": "Conservación de la Naturaleza", "slug": "conservacion-de-la-naturaleza" },
    { "title": "Protección del Medio Ambiente", "slug": "proteccion-del-medio-ambiente" },
    { "title": "Política Ambiental", "slug": "politica-ambiental" },
    { "title": "Educación Ambiental", "slug": "educacion-ambiental" },
    { "title": "Turismo Sostenible", "slug": "turismo-sostenible" },
    { "title": "Desarrollo Sostenible", "slug": "desarrollo-sostenible" },
    { "title": "Economía Circular", "slug": "economia-circular" },
    { "title": "Agua", "slug": "agua" },
    { "title": "Aire", "slug": "aire" },
    { "title": "Suelo", "slug": "suelo" },
    { "title": "Biodiversidad", "slug": "biodiversidad" },
    { "title": "Ecosistemas", "slug": "ecosistemas" },
    { "title": "Fauna", "slug": "fauna" },
    { "title": "Flora", "slug": "flora" },
    { "title": "Biología", "slug": "biologia" },
    { "title": "Ecología", "slug": "ecologia" },
    { "title": "Geología", "slug": "geologia" },
    { "title": "Oceanografía", "slug": "oceanografia" },
    { "title": "Meteorología", "slug": "meteorologia" },
    { "title": "Climatología", "slug": "climatologia" },
    { "title": "Geografía", "slug": "geografia" },
    { "title": "Espacio", "slug": "espacio" },
    { "title": "Universo", "slug": "universo" },
    { "title": "Astronáutica", "slug": "astronautica" },
    { "title": "Cosmología", "slug": "cosmologia" },
    { "title": "Exoplanetas", "slug": "exoplanetas" },
    { "title": "Agujeros Negros", "slug": "agujeros-negros" },
    { "title": "Galaxias", "slug": "galaxias" },
    { "title": "Constelaciones", "slug": "constelaciones" },
    { "title": "Estrellas", "slug": "estrellas" },
    { "title": "Planetas", "slug": "planetas" },
    { "title": "Lunas", "slug": "lunas" },
    { "title": "Asteroides", "slug": "asteroides" },
    { "title": "Meteoritos", "slug": "meteoritos" },
    { "title": "Cometas", "slug": "cometas" },
    { "title": "Física", "slug": "fisica" },
    { "title": "Química", "slug": "quimica" },
    { "title": "Biología", "slug": "biologia" },
    { "title": "Matemáticas", "slug": "matematicas" },
    { "title": "Ciencias de la Computación", "slug": "ciencias-de-la-computacion" },
    { "title": "Ingeniería", "slug": "ingenieria" },
    { "title": "Medicina", "slug": "medicina" },
    { "title": "Neurociencia", "slug": "neurociencia" },
    { "title": "Psicología", "slug": "psicologia" },
    { "title": "Sociología", "slug": "sociologia" },
    { "title": "Antropología", "slug": "antropologia" },
    { "title": "Arqueología", "slug": "arqueologia" },
    { "title": "Paleontología", "slug": "paleontologia" },
    { "title": "Historia", "slug": "historia" },
    { "title": "Arte", "slug": "arte" },
    { "title": "Música", "slug": "musica" },
    { "title": "Cine", "slug": "cine" },
    { "title": "Teatro", "slug": "teatro" },
    { "title": "Danza", "slug": "danza" },
    { "title": "Literatura", "slug": "literatura" },
    { "title": "Pintura", "slug": "pintura" },
    { "title": "Escultura", "slug": "escultura" },
    { "title": "Arquitectura", "slug": "arquitectura" },
    { "title": "Fotografía", "slug": "fotografia" },
    { "title": "Diseño", "slug": "diseno" },
    { "title": "Moda", "slug": "moda" },
    { "title": "Cocina", "slug": "cocina" },
    { "title": "Gastronomía", "slug": "gastronomia" },
    { "title": "Nutrición", "slug": "nutricion" },
    { "title": "Restauración", "slug": "restauracion" },
    { "title": "Salud", "slug": "salud" },
    { "title": "Medicina Alternativa", "slug": "medicina-alternativa" },
    { "title": "Bienestar", "slug": "bienestar" },
    { "title": "Fitness", "slug": "fitness" },
    { "title": "Deportes", "slug": "deportes" },
    { "title": "Yoga", "slug": "yoga" },
    { "title": "Pilates", "slug": "pilates" },
    { "title": "Running", "slug": "running" },
    { "title": "Ciclismo", "slug": "ciclismo" },
    { "title": "Natación", "slug": "natacion" },
    { "title": "Atletismo", "slug": "atletismo" },
    { "title": "Fútbol", "slug": "futbol" },
    { "title": "Baloncesto", "slug": "baloncesto" },
    { "title": "Tenis", "slug": "tenis" },
    { "title": "Golf", "slug": "golf" },
    { "title": "Rugby", "slug": "rugby" },
    { "title": "Críquet", "slug": "criquet" },
    { "title": "Boxeo", "slug": "boxeo" },
    { "title": "Artes Marciales", "slug": "artes-marciales" },
    { "title": "Hípica", "slug": "hipica" },
    { "title": "Montañismo", "slug": "montanismo" },
    { "title": "Escalada", "slug": "escalada" },
    { "title": "Esquí", "slug": "esqui" },
    { "title": "Snowboard", "slug": "snowboard" },
    { "title": "Surf", "slug": "surf" },
    { "title": "Kitesurf", "slug": "kitesurf" },
    { "title": "Windsurf", "slug": "windsurf" },
    { "title": "Vela", "slug": "vela" },
    { "title": "Pesca", "slug": "pesca" },
    { "title": "Caza", "slug": "caza" },
    { "title": "Buceo", "slug": "buceo" },
    { "title": "Ecoturismo", "slug": "ecoturismo" },
    { "title": "Turismo de Aventura", "slug": "turismo-de-aventura" },
    { "title": "Turismo Rural", "slug": "turismo-rural" },
    { "title": "Turismo Cultural", "slug": "turismo-cultural" },
    { "title": "Turismo de Lujo", "slug": "turismo-de-lujo" },
    { "title": "Turismo Gastronómico", "slug": "turismo-gastronomico" },
    { "title": "Turismo Religioso", "slug": "turismo-religioso" },
    { "title": "Turismo de Salud", "slug": "turismo-de-salud" },
    { "title": "Turismo de Bienestar", "slug": "turismo-de-bienestar" },
    { "title": "Turismo Náutico", "slug": "turismo-nautico" },
    { "title": "Turismo de Cruceros", "slug": "turismo-de-cruceros" },
    { "title": "Turismo de Aventura", "slug": "turismo-de-aventura" },
    { "title": "Turismo Deportivo", "slug": "turismo-deportivo" },
    { "title": "Turismo de Naturaleza", "slug": "turismo-de-naturaleza" },
    { "title": "Turismo de Montaña", "slug": "turismo-de-montana" },
    { "title": "Turismo Urbano", "slug": "turismo-urbano" },
    { "title": "Turismo Patrimonial", "slug": "turismo-patrimonial" },
    { "title": "Turismo Industrial", "slug": "turismo-industrial" },
    { "title": "Turismo Cinematográfico", "slug": "turismo-cinematografico" },
    { "title": "Turismo Espacial", "slug": "turismo-espacial" },
    { "title": "Turismo Místico", "slug": "turismo-mistico" },
    { "title": "Turismo de Compras", "slug": "turismo-de-compras" },
    { "title": "Turismo LGBT", "slug": "turismo-lgbt" },
    { "title": "Turismo Sostenible", "slug": "turismo-sostenible" },
    { "title": "Turismo Educativo", "slug": "turismo-educativo" },
    { "title": "Turismo Solidario", "slug": "turismo-solidario" },
    { "title": "Turismo Responsable", "slug": "turismo-responsable" },
    { "title": "Turismo Accesible", "slug": "turismo-accesible" },
    { "title": "Turismo de Festivales", "slug": "turismo-de-festivales" },
    { "title": "Turismo de Boda", "slug": "turismo-de-boda" },
    { "title": "Turismo de Naturaleza", "slug": "turismo-de-naturaleza" },
    { "title": "Turismo de Descanso", "slug": "turismo-de-descanso" },
    { "title": "Turismo de Deportes Extremos", "slug": "turismo-de-deportes-extremos" },
    { "title": "Turismo de Aventura", "slug": "turismo-de-aventura" },
    { "title": "Turismo Rural", "slug": "turismo-rural" },
    { "title": "Turismo Gastronómico", "slug": "turismo-gastronomico" },
    { "title": "Turismo Cultural", "slug": "turismo-cultural" },
    { "title": "Turismo de Lujo", "slug": "turismo-de-lujo" },
    { "title": "Turismo de Bienestar", "slug": "turismo-de-bienestar" },
    { "title": "Turismo de Salud", "slug": "turismo-de-salud" },
    { "title": "Turismo de Bienestar", "slug": "turismo-de-bienestar" },
    { "title": "Turismo de Aventura", "slug": "turismo-de-aventura" },
    { "title": "Turismo de Deportes", "slug": "turismo-de-deportes" },
    { "title": "Turismo de Naturaleza", "slug": "turismo-de-naturaleza" },
    { "title": "Turismo de Montaña", "slug": "turismo-de-montana" },
    { "title": "Turismo de Playa", "slug": "turismo-de-playa" },
    { "title": "Turismo de Ciudad", "slug": "turismo-de-ciudad" },
    { "title": "Turismo de Carretera", "slug": "turismo-de-carretera" },
    { "title": "Turismo de Aventura", "slug": "turismo-de-aventura" },
    { "title": "Turismo Rural", "slug": "turismo-rural" },
    { "title": "Turismo de Montaña", "slug": "turismo-de-montana" },
    { "title": "Turismo de Aventura", "slug": "turismo-de-aventura" },
    { "title": "Turismo Cultural", "slug": "turismo-cultural" },
    { "title": "Turismo de Lujo", "slug": "turismo-de-lujo" },
    { "title": "Turismo de Aventura", "slug": "turismo-de-aventura" },
    { "title": "Fotografía", "slug": "fotografia" },
    { "title": "Diseño gráfico", "slug": "diseno-grafico" },
    { "title": "Diseño web", "slug": "diseno-web" },
    { "title": "Edición de imágenes", "slug": "edicion-de-imagenes" },
    { "title": "Ilustración", "slug": "ilustracion" },
    { "title": "Fotografía de moda", "slug": "fotografia-de-moda" },
    { "title": "Fotografía de paisajes", "slug": "fotografia-de-paisajes" },
    { "title": "Fotografía de retratos", "slug": "fotografia-de-retratos" },
    { "title": "Fotografía de bodas", "slug": "fotografia-de-bodas" },
    { "title": "Fotografía de viajes", "slug": "fotografia-de-viajes" },
    { "title": "Medicina", "slug": "medicina" },
    { "title": "Nutrición", "slug": "nutricion" },
    { "title": "Enfermería", "slug": "enfermeria" },
    { "title": "Farmacología", "slug": "farmacologia" },
    { "title": "Terapia física", "slug": "terapia-fisica" },
    { "title": "Terapia ocupacional", "slug": "terapia-ocupacional" },
    { "title": "Odontología", "slug": "odontologia" },
    { "title": "Optometría", "slug": "optometria" },
    { "title": "Psiquiatría", "slug": "psiquiatria" },
    { "title": "Pediatría", "slug": "pediatria" },
    { "title": "Educación primaria", "slug": "educacion-primaria" },
    { "title": "Educación secundaria", "slug": "educacion-secundaria" },
    { "title": "Educación universitaria", "slug": "educacion-universitaria" },
    { "title": "Educación a distancia", "slug": "educacion-a-distancia" },
    { "title": "Educación especial", "slug": "educacion-especial" },
    { "title": "Pedagogía", "slug": "pedagogia" },
    { "title": "Didáctica", "slug": "didactica" },
    { "title": "Aprendizaje online", "slug": "aprendizaje-online" },
    { "title": "Técnicas de estudio", "slug": "tecnicas-de-estudio" },
    { "title": "Tutoría académica", "slug": "tutoria-academica" },
    { "title": "Viajes de aventura", "slug": "viajes-de-aventura" },
    { "title": "Ecoturismo", "slug": "ecoturismo" },
    { "title": "Turismo rural", "slug": "turismo-rural" },
    { "title": "Turismo de montaña", "slug": "turismo-de-montana" },
    { "title": "Turismo de playa", "slug": "turismo-de-playa" },
    { "title": "Turismo cultural", "slug": "turismo-cultural" },
    { "title": "Turismo gastronómico", "slug": "turismo-gastronomico" },
    { "title": "Turismo de lujo", "slug": "turismo-de-lujo" },
    { "title": "Turismo deportivo", "slug": "turismo-deportivo" },
    { "title": "Turismo de naturaleza", "slug": "turismo-de-naturaleza" },
    { "title": "Marketing digital", "slug": "marketing-digital" },
    { "title": "Publicidad online", "slug": "publicidad-online" },
    { "title": "Estrategias de marketing", "slug": "estrategias-de-marketing" },
    { "title": "Marketing de contenidos", "slug": "marketing-de-contenidos" },
    { "title": "Publicidad en redes sociales", "slug": "publicidad-en-redes-sociales" },
    { "title": "Branding", "slug": "branding" },
    { "title": "Marketing de influencers", "slug": "marketing-de-influencers" },
    { "title": "Publicidad nativa", "slug": "publicidad-nativa" },
    { "title": "Marketing de afiliados", "slug": "marketing-de-afiliados" },
    { "title": "Marketing de guerrilla", "slug": "marketing-de-guerrilla" },
    { "title": "Desarrollo web", "slug": "desarrollo-web" },
    { "title": "Desarrollo móvil", "slug": "desarrollo-movil" },
    { "title": "Desarrollo de software", "slug": "desarrollo-de-software" },
    { "title": "Tecnología blockchain", "slug": "tecnologia-blockchain" },
    { "title": "Seguridad informática", "slug": "seguridad-informatica" },
    { "title": "Internet de las cosas", "slug": "internet-de-las-cosas" },
    { "title": "Realidad aumentada", "slug": "realidad-aumentada" },
    { "title": "Realidad virtual", "slug": "realidad-virtual" },
    { "title": "Inteligencia artificial", "slug": "inteligencia-artificial" },
    { "title": "Ciberseguridad", "slug": "ciberseguridad" },
    { "title": "Negocios", "slug": "negocios" },
    { "title": "Finanzas", "slug": "finanzas" },
    { "title": "Emprendimiento", "slug": "emprendimiento" },
    { "title": "Marketing", "slug": "marketing" },
    { "title": "Ventas", "slug": "ventas" },
    { "title": "Inversiones", "slug": "inversiones" },
    { "title": "Gestión del Tiempo", "slug": "gestion-del-tiempo" },
    { "title": "Recursos Humanos", "slug": "recursos-humanos" },
    { "title": "Liderazgo", "slug": "liderazgo" },
    { "title": "Contabilidad", "slug": "contabilidad" },
    { "title": "Salud", "slug": "salud" },
    { "title": "Fitness", "slug": "fitness" },
    { "title": "Nutrición", "slug": "nutricion" },
    { "title": "Medicina", "slug": "medicina" },
    { "title": "Bienestar", "slug": "bienestar" },
    { "title": "Yoga", "slug": "yoga" },
    { "title": "Pilates", "slug": "pilates" },
    { "title": "Running", "slug": "running" },
    { "title": "Ciclismo", "slug": "ciclismo" },
    { "title": "Natación", "slug": "natacion" },
    { "title": "Arte", "slug": "arte" },
    { "title": "Literatura", "slug": "literatura" },
    { "title": "Música", "slug": "musica" },
    { "title": "Cine", "slug": "cine" },
    { "title": "Fotografía", "slug": "fotografia" },
    { "title": "Diseño", "slug": "diseno" },
    { "title": "Pintura", "slug": "pintura" },
    { "title": "Escultura", "slug": "escultura" },
    { "title": "Arquitectura", "slug": "arquitectura" },
    { "title": "Danza", "slug": "danza" },
    { "title": "Ciencia", "slug": "ciencia" },
    { "title": "Historia", "slug": "historia" },
    { "title": "Astronomía", "slug": "astronomia" },
    { "title": "Biología", "slug": "biologia" },
    { "title": "Física", "slug": "fisica" },
    { "title": "Matemáticas", "slug": "matematicas" },
    { "title": "Psicología", "slug": "psicologia" },
    { "title": "Sociología", "slug": "sociologia" },
    { "title": "Educación", "slug": "educacion" },
    { "title": "Neurociencia", "slug": "neurociencia" },
    { "title": "Viajes", "slug": "viajes" },
    { "title": "Turismo Rural", "slug": "turismo-rural" },
    { "title": "Turismo Cultural", "slug": "turismo-cultural" },
    { "title": "Turismo de Aventura", "slug": "turismo-de-aventura" },
    { "title": "Turismo de Playa", "slug": "turismo-de-playa" },
    { "title": "Turismo de Montaña", "slug": "turismo-de-montana" },
    { "title": "Turismo Gastronómico", "slug": "turismo-gastronomico" },
    { "title": "Ecoturismo", "slug": "ecoturismo" },
    { "title": "Turismo Urbano", "slug": "turismo-urbano" },
    { "title": "Turismo de Naturaleza", "slug": "turismo-de-naturaleza" },
]





for tag_data in tags:
    tag = Tag.objects.filter(slug=tag_data['slug']).first()
    
    # Si el tag existe, elimínalo
    if tag:
        tag.delete()
        print(f'Tag "{tag_data["title"]}" eliminado')
    
    # Crea el tag
    name = tag_data['title']
    print('este es el name luego de borrar: '+name)
    tag, created = Tag.objects.get_or_create(slug=tag_data['slug'], defaults={'name': name})
    if created:
        print(f'Tag "{tag.name}" creado exitosamente')
    else:
        print(f'Tag "{tag.name}" ya existe en la base de datos') 